[package]
name = "solids_bench_quad"
description = "static quad pipeline benchmarks for solids"
version.workspace = true
edition.workspace = true
repository.workspace = true
licence.workspace = true

[dependencies]
iced.workspace = true
env_logger.workspace = true